export const eventList = [
  {
    date: 'March 2016',
    venue: 'Call-Em-All',
    speaker1: 'Morry Kang',
    topic1: 'Intro to React',
  },
  {
    date: 'April 2016',
    venue: 'Call-Em-All',
    speaker1: 'Chris LeBlanc',
    speaker2: 'Geoffrey Abdallah',
    topic1: 'React Native',
    topic2: 'State Management in React',
  },
  {
    date: 'May 2016',
    venue: 'Copart',
    speaker1: 'Emmanuel Morales',
    topic1: 'Introduction to React Data Flow',
  },
  {
    date: 'June 2016',
    venue: 'Kowork',
    speaker1: '',
    topic1: 'Social Coding @ Kowork'
  },
  {
    date: 'July 2016',
    venue: 'One Technologies',
    speaker1: 'Doug Johnson',
    topic1: 'Using React in a Wordpress Environment',
  },
  {
    date: 'August 2016',
    venue: 'Match',
    speaker1: 'Mike Mathew',
    speaker2: 'Derek Crabtree',
    topic1: 'Create a React App Easily',
    topic2: 'Moving Match to React',
  },
  {
    date: 'January 2018',
    venue: 'The Container Store',
    speaker1: 'Ryan Boone',
    topic1: 'ImmutableJS'
  },
  {
    date: 'May 2018',
    venue: 'Pearl Technology',
    speaker1: 'Joe Warren',
    speaker2: 'Tony Spiro',
    topic1: 'Web Development Internships: A View from the Inside',
    topic2: 'Building for Team Success with Content-Powered Apps',
  },
  {
    date: 'June 2018',
    venue: 'Improving',
    speaker1: 'Austin Chappell',
    speaker2: 'John Dahl',
    topic1: 'React-Native: Bridging the Gap',
    topic2: 'ADA Web Accessibility in React',
  },
  {
    date: 'June 2019',
    venue: 'Call-Em-All',
    speaker1: 'Salvador Aceves',
    speaker2: 'Mike Mathew',
    topic1: 'Setting up docker for testing with Cypress',
    topic2: 'React 102',
  },
  {
    date: 'March 2022',
    venue: 'Text-Em-All',
    speaker1: 'Mike Mathew',
    speaker2: 'Mike Mathew',
    topic1: 'Something broke in production, now what?',
    topic2: 'Upgrading from Material-UI v4 to v5',
  },
  {
    date: 'May 2022',
    venue: 'Text-Em-All',
    speaker1: 'Patrick Hulce',
    topic1: 'React Performance: Profiling & v18 Improvements',
  },
  {
    date: 'June 2022',
    venue: 'Text-Em-All',
    speaker1: 'Mike Mathew',
    topic1: 'React 101',
  },
  {
    date: 'JuLy 2022',
    venue: 'Text-Em-All',
    speaker1: 'Humberto Lopez',
    topic1: 'Debugging React and Javascript',
  },
];
